name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      API_TOKEN: ${{ secrets.API_TOKEN }}
  
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: true

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: deps
      run: make deps

    - name: make
      run: make sbom

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: Ben Timby
        author_email: btimby@gmail.com
        message: 'Updated SBOM'
        add: 'sbom.html'
